### ISSUE TITLE
Initial Front Page Redesign V3 Planning

### ISSUE THREAD

**Issue by rjcorwin** [FarmHack/FarmHack.org#1]
See prototype here -> http://farmhack.github.io/farm-hack-website-prototypes/
- [ ] Set up `home2` folder with initial Backbone app scaffolding going #8
- [ ] Front page Menu #2
- [ ] Ability for Administrator to curate content for the front page #9
- [ ] Featured Tools View #4
- [ ] Set up apache_solr module to index Tools
- [ ] Front page search widget (Front page is the tools search? Use Solarita.js or Recliner.js?)
- [ ] Refactor front page redirect to be JS based, nonJS frontpage a list of content, JS redirect to appropriate JS route if node page is requested directly
