### ISSUE TITLE
New Tools Section Go Live Checklist

### ISSUE THREAD

**Issue by rjcorwin** [FarmHack/FarmHack.org#47]
- [x] Change all `tools/[name]` paths to `archive/[name]` and `library/[name]` to `tools/[name]`
- [x] Add notification block to top of all Tools in the archive that they are archived.
- [x] Run content migration
- [ ] Post blog announcement

**Comment by danibgrover** [comment]
Change help text in "Because" portion of problem statement form to reflect the change we made: you can no longer add multiple "Because" statements.

**Comment by rjcorwin** [comment]
@danielbgrover I changed that Because help text. http://farmhack.org/node/add/problem-statement
