### ISSUE TITLE
New Tool Library Launch checklist

### ISSUE THREAD

**Issue by rjcorwin** [FarmHack/FarmHack.org#49]
- [ ] Set message on all old tools that they are archived. Link to the same tool in the new tool library if possible.
- [ ] Move the new tool library to `/tools` and move the old tool library to `/archive/tools`.
- [ ] Make sure the new mobile theme is enabled in the correct places.
- [ ] Tests the new tool library when everything is in place.
- [ ] Release blog post.
